name = "mini-tds"
main = "src/worker.ts"
compatibility_date = "2024-11-01"

routes = [
  { pattern = "bookieranks.ru/*", zone_name = "bookieranks.ru" }
]

kv_namespaces = [
  { binding = "KV", id = "a7ef054cee4b435f996060e458f7beef" }
]
